modLoader = "javafml"
loaderVersion = "[1.11,)"
issueTrackerURL = "https://github.com/Devan-Kerman/Fields-API/issues"
license = "MPLv2"

[[mods]]
modId = "fields-api"
version = "${version}"
displayName = "Fields API"
authors = "HalfOf2"
description = '''
	Fields API
'''
logoFile = "icon.png"

[[dependencies.fields-api]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fields-api]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"